<?php

namespace Database\Seeders;

use App\Models\GeneralSetting;
use Illuminate\Database\Seeder;

class GeneralSettingsSeeder extends Seeder
{
    public function run()
    {
        GeneralSetting::create([
            'sitename' => 'My Application',
            'fiat_api_key' => 'your_fiat_api_key',
            'crypto_api_key' => 'your_crypto_api_key',
            'public_key' => 'your_public_key',
            'private_key' => 'your_private_key',
            'merchant_id' => 'your_merchant_id',
            'dark' => 0,
            'cur_text' => 'USD',
            'cur_sym' => '$',
            'email_from' => 'noreply@example.com',
            'sms_api' => 'your_sms_api',
            'base_color' => '#ffffff',
            'secondary_color' => '#000000',
            'mail_config' => json_encode(['driver' => 'smtp']),
            'sms_config' => json_encode(['provider' => 'twilio']),
            'ev' => 1,
            'en' => 1,
            'sv' => 1,
            'sn' => 1,
            'va' => 1,
            'cd' => 1,
            'force_ssl' => 1,
            'secure_password' => 1,
            'agree' => 1,
            'registration' => 1,
            'active_template' => 'default',
            'sys_version' => '1.0.0',
            'last_cron' => now(),
            'modules' => json_encode(['module1', 'module2']),
            'reloadly_id' => 'your_reloadly_id',
            'reloadly_secret' => 'your_reloadly_secret',
            'reloadly' => 1,
            'flutterwave_secret' => 'your_flutterwave_secret',
            'flutterwave_public' => 'your_flutterwave_public',
            'flutterwave_merchant' => 'your_flutterwave_merchant',
            'ezpin_secret' => 'your_ezpin_secret',
            'ezpin_id' => 'your_ezpin_id',
            'doc' => 'your_doc',
            'usd_fee' => 0.00,
            'ngn_fee' => 0.00,
            'load_fee' => 0.00,
            'pg_fee' => 0.00,
            'tx_fee' => 0.00,
            'ev_fee' => 0.00,
            'merchant_key' => 'your_merchant_key',
            'card_bin' => 'your_card_bin',
            'apto_url' => 'your_apto_url',
            'apto_mobile_key' => 'your_apto_mobile_key',
            'apto_public_key' => 'your_apto_public_key',
            'apto_secret_key' => 'your_apto_secret_key',
            'apto_balance_id' => 'your_apto_balance_id',
            'verifai' => 'your_verifai',
            'deposit_commission' => 1,
            'invest_commission' => 1,
            'invest_return_commission' => 1,
            'signup_bonus_amount' => 0.00,
            'signup_bonus_control' => 1,
            'off_day' => json_encode(['Sunday']),
            'b_transfer' => 1,
            'f_charge' => 0.00,
            'p_charge' => 0.00,
            'user_cashout' => 0.00,
            'user_cashin' => 0.00,
            'agent_cashpay' => 0.00,
            'agent_cashrcv' => 0.00,
            'verifai_act' => 0,
            'tremendous' => 0,
            'tremendous_key' => 'your_tremendous_key',
            'tremendous_us' => 'your_tremendous_us',
            'tremendous_row' => 'your_tremendous_row',
            'tremendous_mode' => 'your_tremendous_mode',
            'usdvisa_fee' => 0.00,
            'livitpay' => 0,
            'livitpay_public' => 'your_livitpay_public',
            'livitpay_private' => 'your_livitpay_private',
            'tatum_mode' => 'your_tatum_mode',
            'tatum_key' => 'your_tatum_key',
            'stripePublishableKey' => 'your_stripe_publishable_key',
            'stripeuniquekey' => 'your_stripe_unique_key',
            'stripeSecretKey' => 'your_stripe_secret_key',
            'kyc' => 1,
            'juvidoe_mode' => 0,
            'dps' => 0,
            'loan' => 0,
            'fdr' => 0,
            'crypto_monthly' => 0.00,
            'fiat_monthly' => 0.00,
            'kyc_modules' => json_encode(['module1', 'module2']),
            'transfers' => 1,
            'vtpusername' => 'your_vtp_username',
            'vtppassword' => 'your_vtp_password',
            'vtpurl' => 'your_vtp_url',
            'fincra_secretkey' => 'your_fincra_secretkey',
            'kuda_email' => 'your_kuda_email',
            'kuda_apikey' => 'your_kuda_apikey',
            'kuda_url' => 'your_kuda_url',
            'payment_deposit' => 1,
            'user_transfer' => 1,
            'payment_withdrawal' => 1,
            'plaid_client' => 'your_plaid_client',
            'plaid_secret' => 'your_plaid_secret',
            'plaid_url' => 'your_plaid_url',
        ]);
    }
}